// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/nullable"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	Oauth2Scopes = "oauth2.Scopes"
)

// Defines values for ErrorCode.
const (
	CONFLICT         ErrorCode = "CONFLICT"
	INTERNAL         ErrorCode = "INTERNAL"
	NOTFOUND         ErrorCode = "NOT_FOUND"
	PERMISSIONDENIED ErrorCode = "PERMISSION_DENIED"
	RATELIMITED      ErrorCode = "RATE_LIMITED"
	UNAUTHENTICATED  ErrorCode = "UNAUTHENTICATED"
	VALIDATIONERROR  ErrorCode = "VALIDATION_ERROR"
)

// Defines values for IntrospectionTokenType.
const (
	IntrospectionTokenTypeBearer IntrospectionTokenType = "Bearer"
)

// Defines values for LivenessStatusStatus.
const (
	Ok LivenessStatusStatus = "ok"
)

// Defines values for OAuthErrorError.
const (
	InvalidClient        OAuthErrorError = "invalid_client"
	InvalidGrant         OAuthErrorError = "invalid_grant"
	InvalidRequest       OAuthErrorError = "invalid_request"
	InvalidScope         OAuthErrorError = "invalid_scope"
	ServerError          OAuthErrorError = "server_error"
	UnauthorizedClient   OAuthErrorError = "unauthorized_client"
	UnsupportedGrantType OAuthErrorError = "unsupported_grant_type"
)

// Defines values for OrganizationStatus.
const (
	OrganizationStatusActive    OrganizationStatus = "active"
	OrganizationStatusSuspended OrganizationStatus = "suspended"
)

// Defines values for OrganizationSettingsAllowedLoginMethods.
const (
	Password OrganizationSettingsAllowedLoginMethods = "password"
)

// Defines values for OrganizationUpdateStatus.
const (
	OrganizationUpdateStatusActive    OrganizationUpdateStatus = "active"
	OrganizationUpdateStatusSuspended OrganizationUpdateStatus = "suspended"
)

// Defines values for ReadinessStatusStatus.
const (
	Ready       ReadinessStatusStatus = "ready"
	Unavailable ReadinessStatusStatus = "unavailable"
)

// Defines values for TokenResponseTokenType.
const (
	TokenResponseTokenTypeBearer TokenResponseTokenType = "Bearer"
)

// Error The error envelope for every non-2xx response, without exception
// (`docs/PLAN/05` Part B § Standard Error Format). One shape means a client
// writes one error path rather than one per endpoint.
type Error struct {
	Error struct {
		// Code A stable, machine-readable code. Clients branch on this; `message` is
		// for humans and may be reworded at any time without a version bump.
		//
		// Deliberately coarse. A code per failure mode leaks internal structure
		// and becomes an enumeration oracle — `USER_NOT_FOUND` versus
		// `PERMISSION_DENIED` tells an attacker which addresses are registered
		// (`docs/SECURITY/02` §12).
		Code ErrorCode `json:"code"`

		// Details Field-level problems. Omitted when there are none.
		Details *[]ErrorDetail `json:"details,omitempty"`

		// Message Human-readable, safe to surface in a UI, and never containing a
		// token, a password, a raw `/v1/authz/check` resource attribute,
		// a stack trace, or a SQL fragment (`docs/PLAN/13`, `CLAUDE.md`).
		Message string `json:"message"`
	} `json:"error"`
}

// ErrorCode A stable, machine-readable code. Clients branch on this; `message` is
// for humans and may be reworded at any time without a version bump.
//
// Deliberately coarse. A code per failure mode leaks internal structure
// and becomes an enumeration oracle — `USER_NOT_FOUND` versus
// `PERMISSION_DENIED` tells an attacker which addresses are registered
// (`docs/SECURITY/02` §12).
type ErrorCode string

// ErrorDetail One specific problem within a failed request. Present for
// `VALIDATION_ERROR`, where naming the bad field is helpful and discloses
// nothing the caller did not send. Generally absent otherwise.
type ErrorDetail struct {
	// Field JSON path to the offending field, relative to the request body.
	Field string `json:"field"`

	// Issue What is wrong with it, in plain language.
	Issue string `json:"issue"`
}

// Introspection RFC 7662's response. When `active` is false it is the ONLY property
// present - every negative case answers identically, so nothing here can
// be used to tell them apart.
type Introspection struct {
	// Active Whether the token is currently usable.
	Active bool    `json:"active"`
	Aud    *string `json:"aud,omitempty"`

	// ClientId The client the token was issued to - always your own.
	ClientId *openapi_types.UUID `json:"client_id,omitempty"`
	Exp      *int64              `json:"exp,omitempty"`
	Iat      *int64              `json:"iat,omitempty"`
	Iss      *string             `json:"iss,omitempty"`

	// Scope Space-delimited, as granted.
	Scope *string `json:"scope,omitempty"`

	// Sub The user. Absent for a `client_credentials` token.
	Sub       *openapi_types.UUID     `json:"sub,omitempty"`
	TokenType *IntrospectionTokenType `json:"token_type,omitempty"`
}

// IntrospectionTokenType defines model for Introspection.TokenType.
type IntrospectionTokenType string

// JWK One public key, per RFC 7517. Private parameters (`d`, `p`, `q`, `dp`,
// `dq`, `qi`) never appear.
type JWK struct {
	Alg *string `json:"alg,omitempty"`

	// Crv EC curve, for ES256 keys.
	Crv *string `json:"crv,omitempty"`

	// E RSA public exponent, base64url.
	E *string `json:"e,omitempty"`

	// Kid An RFC 7638 thumbprint of the key, so it is stable across restarts
	// and cannot be chosen by anyone.
	Kid string `json:"kid"`
	Kty string `json:"kty"`

	// N RSA modulus, base64url.
	N   *string `json:"n,omitempty"`
	Use string  `json:"use"`
	X   *string `json:"x,omitempty"`
	Y   *string `json:"y,omitempty"`
}

// JWKS defines model for JWKS.
type JWKS struct {
	Keys []JWK `json:"keys"`
}

// LivenessStatus The complete `/healthz` response. There are no other fields, and none
// will be added that name a dependency or a version.
type LivenessStatus struct {
	Status LivenessStatusStatus `json:"status"`
}

// LivenessStatusStatus defines model for LivenessStatus.Status.
type LivenessStatusStatus string

// OAuthError OAuth 2.1's error shape (RFC 6749 § 5.2), used by the protocol
// endpoints. Distinct from the `Error` envelope every other endpoint
// returns, because this is what a consumer's OAuth library parses.
type OAuthError struct {
	Error OAuthErrorError `json:"error"`

	// ErrorDescription Human-readable, and deliberately terse about specifics. It names
	// what was wrong, never what the correct value would have been.
	ErrorDescription *string `json:"error_description,omitempty"`
}

// OAuthErrorError defines model for OAuthError.Error.
type OAuthErrorError string

// OpenIDConfiguration OpenID Provider metadata. Fields for unimplemented endpoints are
// omitted rather than emitted empty.
type OpenIDConfiguration struct {
	// AuthorizationEndpoint Present once the authorization endpoint exists.
	AuthorizationEndpoint *string   `json:"authorization_endpoint,omitempty"`
	ClaimsSupported       *[]string `json:"claims_supported,omitempty"`

	// CodeChallengeMethodsSupported `S256` only. Never `plain`.
	CodeChallengeMethodsSupported *[]string `json:"code_challenge_methods_supported,omitempty"`
	EndSessionEndpoint            *string   `json:"end_session_endpoint,omitempty"`

	// GrantTypesSupported Never contains `implicit` or `password`: both are ruled out
	// permanently by `docs/PLAN/05` § Supported Grant Types, and advertising
	// a grant this service refuses invites a client to build against it.
	GrantTypesSupported              *[]string `json:"grant_types_supported,omitempty"`
	IdTokenSigningAlgValuesSupported []string  `json:"id_token_signing_alg_values_supported"`
	IntrospectionEndpoint            *string   `json:"introspection_endpoint,omitempty"`

	// Issuer The identifier clients validate the `iss` claim against. Compared
	// byte for byte, so it never carries a trailing slash.
	Issuer                 string    `json:"issuer"`
	JwksUri                string    `json:"jwks_uri"`
	ResponseTypesSupported *[]string `json:"response_types_supported,omitempty"`
	RevocationEndpoint     *string   `json:"revocation_endpoint,omitempty"`
	ScopesSupported        *[]string `json:"scopes_supported,omitempty"`

	// SubjectTypesSupported `public` only. Pairwise identifiers are a privacy feature this
	// service does not implement.
	SubjectTypesSupported []string `json:"subject_types_supported"`

	// TokenEndpoint Present once the token endpoint exists.
	TokenEndpoint    *string `json:"token_endpoint,omitempty"`
	UserinfoEndpoint *string `json:"userinfo_endpoint,omitempty"`
}

// Organization A tenant.
//
// `instance_id` is deliberately not exposed. It is an internal grouping
// with one row in this phase, and a field a client can see is a field a
// client will eventually send back.
type Organization struct {
	CreatedAt time.Time `json:"created_at"`

	// Domain For domain-based tenant resolution. Unique across the instance and
	// stored lowercased, because two tenants holding the same domain in
	// different cases would make tenant resolution ambiguous — and an
	// ambiguous tenant resolution is a cross-tenant access bug waiting to
	// happen. Verification of ownership is a later phase.
	Domain nullable.Nullable[string] `json:"domain,omitempty"`

	// Id A resource's stable identifier. Not sequential and not guessable.
	//
	// **This was specified as a prefixed, sortable identifier** — `usr_`,
	// `org_`, `prj_` — and is a UUID instead. The change is deliberate and is
	// recorded as `PG-23`.
	//
	// The prefix has a real benefit: an id pasted into a support ticket is
	// self-describing, and passing a project id where a user id belongs is
	// visible on sight rather than at the database. What it cannot survive is
	// being applied to only part of the surface. `docs/PLAN/04` makes every
	// primary key a UUID, the access token's `org_id` claim is a UUID, and
	// OpenID Connect's `sub` — already shipped by `P1-08` — is a UUID that
	// callers store as a user's permanent key.
	//
	// Prefixing only the Management API would give the same user two
	// identifiers and make every consumer convert between them, which is a
	// larger and more permanent papercut than the one the prefix removes.
	// Prefixing everything means changing `sub`, which is a protocol field
	// with its own conventions and a value integrators have already stored.
	//
	// So: UUIDs everywhere, and if prefixed identifiers are wanted later they
	// arrive everywhere at once or not at all.
	Id ResourceId `json:"id"`

	// Name The display name. Not unique — two customers may legitimately be
	// called the same thing, and a uniqueness rule on a display name is a
	// support-ticket generator.
	Name string `json:"name"`

	// Settings The organization's policy (`docs/PLAN/08` Part B).
	//
	// **Unknown properties are rejected rather than stored.** A misspelled
	// key kept silently becomes a policy that is not in force and looks like
	// it is, and nobody notices until the audit that was supposed to find it
	// does not.
	Settings OrganizationSettings `json:"settings"`

	// Status A suspended organization's users cannot log in. Changing this
	// requires `INSTANCE_OWNER`.
	Status    OrganizationStatus `json:"status"`
	UpdatedAt time.Time          `json:"updated_at"`
}

// OrganizationStatus A suspended organization's users cannot log in. Changing this
// requires `INSTANCE_OWNER`.
type OrganizationStatus string

// OrganizationCreate Note what cannot be set: `id`, `status`, `created_at`, and the instance.
// Every one of those is server-set, and a request body with nowhere to put
// them is why a mass-assignment attempt has nothing to land on
// (`docs/SECURITY/02` §11).
type OrganizationCreate struct {
	Domain nullable.Nullable[string] `json:"domain,omitempty"`
	Name   string                    `json:"name"`

	// Settings The organization's policy (`docs/PLAN/08` Part B).
	//
	// **Unknown properties are rejected rather than stored.** A misspelled
	// key kept silently becomes a policy that is not in force and looks like
	// it is, and nobody notices until the audit that was supposed to find it
	// does not.
	Settings *OrganizationSettings `json:"settings,omitempty"`
}

// OrganizationList defines model for OrganizationList.
type OrganizationList struct {
	Organizations []Organization `json:"organizations"`

	// PageInfo The pagination envelope every collection response embeds.
	//
	// Token-based rather than offset-based: an offset re-reads rows that
	// shifted under concurrent writes, silently skipping or duplicating
	// entries. For an audit log or a user list that is a correctness bug that
	// nobody notices.
	PageInfo *PageInfo `json:"page_info,omitempty"`
}

// OrganizationSettings The organization's policy (`docs/PLAN/08` Part B).
//
// **Unknown properties are rejected rather than stored.** A misspelled
// key kept silently becomes a policy that is not in force and looks like
// it is, and nobody notices until the audit that was supposed to find it
// does not.
type OrganizationSettings struct {
	// AllowedLoginMethods Only `password` is available in this phase. `passkey` and `social`
	// are planned and are rejected until they work — an API that accepts
	// a method nothing implements would silently disable every method
	// that does.
	AllowedLoginMethods *[]OrganizationSettingsAllowedLoginMethods `json:"allowed_login_methods,omitempty"`
	MfaRequired         *bool                                      `json:"mfa_required,omitempty"`
	PasswordPolicy      *struct {
		// MaxAgeDays `0` means passwords never expire, which is a real choice rather
		// than an absent value: NIST SP 800-63B argues forced rotation
		// makes passwords worse.
		MaxAgeDays *int `json:"max_age_days,omitempty"`

		// MinLength At least the platform minimum. An organization policy may raise
		// it and never lower it — a tenant setting that can go below the
		// instance floor is a per-tenant way to disable a platform
		// control.
		MinLength        *int  `json:"min_length,omitempty"`
		RequireUppercase *bool `json:"require_uppercase,omitempty"`
	} `json:"password_policy,omitempty"`
	SessionLifetimeHours *int `json:"session_lifetime_hours,omitempty"`
}

// OrganizationSettingsAllowedLoginMethods defines model for OrganizationSettings.AllowedLoginMethods.
type OrganizationSettingsAllowedLoginMethods string

// OrganizationUpdate A partial update. An absent property is left alone; `domain: null`
// releases the domain.
type OrganizationUpdate struct {
	Domain nullable.Nullable[string] `json:"domain,omitempty"`
	Name   *string                   `json:"name,omitempty"`

	// Settings The organization's policy (`docs/PLAN/08` Part B).
	//
	// **Unknown properties are rejected rather than stored.** A misspelled
	// key kept silently becomes a policy that is not in force and looks like
	// it is, and nobody notices until the audit that was supposed to find it
	// does not.
	Settings *OrganizationSettings `json:"settings,omitempty"`

	// Status Requires `INSTANCE_OWNER`.
	Status *OrganizationUpdateStatus `json:"status,omitempty"`
}

// OrganizationUpdateStatus Requires `INSTANCE_OWNER`.
type OrganizationUpdateStatus string

// PageInfo The pagination envelope every collection response embeds.
//
// Token-based rather than offset-based: an offset re-reads rows that
// shifted under concurrent writes, silently skipping or duplicating
// entries. For an audit log or a user list that is a correctness bug that
// nobody notices.
type PageInfo struct {
	// NextPageToken Pass as `page_token` for the following page. **Absent when there
	// are no more results** — the presence of this field is the only
	// valid end-of-collection test. An empty array is not one: a page can
	// legitimately return zero items and still have a next page.
	NextPageToken *string `json:"next_page_token,omitempty"`
}

// ReadinessStatus The complete `/readyz` response.
//
// Note that the ready value is `ready`, not `ok`. The two probes report
// different vocabularies, which was found by writing this spec against
// the running code rather than from memory. It is recorded accurately
// rather than tidied, because a client already parsing `ready` would
// break if the server were changed to match a prettier spec — the spec
// describes what ships (ADR-013).
type ReadinessStatus struct {
	Status ReadinessStatusStatus `json:"status"`
}

// ReadinessStatusStatus defines model for ReadinessStatus.Status.
type ReadinessStatusStatus string

// ResourceId A resource's stable identifier. Not sequential and not guessable.
//
// **This was specified as a prefixed, sortable identifier** — `usr_`,
// `org_`, `prj_` — and is a UUID instead. The change is deliberate and is
// recorded as `PG-23`.
//
// The prefix has a real benefit: an id pasted into a support ticket is
// self-describing, and passing a project id where a user id belongs is
// visible on sight rather than at the database. What it cannot survive is
// being applied to only part of the surface. `docs/PLAN/04` makes every
// primary key a UUID, the access token's `org_id` claim is a UUID, and
// OpenID Connect's `sub` — already shipped by `P1-08` — is a UUID that
// callers store as a user's permanent key.
//
// Prefixing only the Management API would give the same user two
// identifiers and make every consumer convert between them, which is a
// larger and more permanent papercut than the one the prefix removes.
// Prefixing everything means changing `sub`, which is a protocol field
// with its own conventions and a value integrators have already stored.
//
// So: UUIDs everywhere, and if prefixed identifiers are wanted later they
// arrive everywhere at once or not at all.
type ResourceId = openapi_types.UUID

// TokenResponse A successful token response (RFC 6749 § 5.1).
type TokenResponse struct {
	// AccessToken A JWT with `typ: at+jwt`. Verify it against the JWKS at
	// `/.well-known/jwks.json` and check `aud` against yourself.
	AccessToken string `json:"access_token"`

	// ExpiresIn Seconds until the access token expires.
	ExpiresIn int `json:"expires_in"`

	// IdToken Present when the `openid` scope was granted and a user
	// authenticated. Absent on a refresh: nothing was authenticated just
	// now, and an assertion that one had been would be a false statement
	// with a fresh timestamp on it.
	IdToken *string `json:"id_token,omitempty"`

	// RefreshToken Present when the `offline_access` scope was granted. Opaque, not a
	// JWT — it must be revocable, which a stateless token cannot be.
	RefreshToken *string `json:"refresh_token,omitempty"`

	// Scope The granted scope, space-delimited.
	Scope     *string                `json:"scope,omitempty"`
	TokenType TokenResponseTokenType `json:"token_type"`
}

// TokenResponseTokenType defines model for TokenResponse.TokenType.
type TokenResponseTokenType string

// UserInfo The claims the presented access token's scopes authorise.
//
// Only `sub` is guaranteed. Every other property appears when its scope
// was granted AND the underlying value is set — an absent claim means the
// value is not known or not authorised, and the two are deliberately not
// distinguished.
type UserInfo struct {
	// Email Requires the `email` scope. `email_verified` is deliberately not
	// returned: nothing in this service verifies an address yet, and
	// asserting `false` would claim a check that never happened.
	Email *openapi_types.Email `json:"email,omitempty"`

	// Name Display name. Requires the `profile` scope.
	Name *string `json:"name,omitempty"`

	// PreferredUsername Requires the `profile` scope. A user may change it, so it is not
	// an identifier — use `sub`.
	PreferredUsername *string `json:"preferred_username,omitempty"`

	// Sub The user's stable identifier. Not sequential, not guessable, and
	// never the email address — store this as the user's permanent key.
	Sub openapi_types.UUID `json:"sub"`

	// UpdatedAt Seconds since the epoch, when the user record last changed
	// (OIDC Core 5.1). Requires the `profile` scope.
	UpdatedAt *int64 `json:"updated_at,omitempty"`
}

// IdempotencyKey defines model for IdempotencyKey.
type IdempotencyKey = string

// OrganizationId A resource's stable identifier. Not sequential and not guessable.
//
// **This was specified as a prefixed, sortable identifier** — `usr_`,
// `org_`, `prj_` — and is a UUID instead. The change is deliberate and is
// recorded as `PG-23`.
//
// The prefix has a real benefit: an id pasted into a support ticket is
// self-describing, and passing a project id where a user id belongs is
// visible on sight rather than at the database. What it cannot survive is
// being applied to only part of the surface. `docs/PLAN/04` makes every
// primary key a UUID, the access token's `org_id` claim is a UUID, and
// OpenID Connect's `sub` — already shipped by `P1-08` — is a UUID that
// callers store as a user's permanent key.
//
// Prefixing only the Management API would give the same user two
// identifiers and make every consumer convert between them, which is a
// larger and more permanent papercut than the one the prefix removes.
// Prefixing everything means changing `sub`, which is a protocol field
// with its own conventions and a value integrators have already stored.
//
// So: UUIDs everywhere, and if prefixed identifiers are wanted later they
// arrive everywhere at once or not at all.
type OrganizationId = ResourceId

// PageSize defines model for PageSize.
type PageSize = int

// PageToken defines model for PageToken.
type PageToken = string

// BadRequest The error envelope for every non-2xx response, without exception
// (`docs/PLAN/05` Part B § Standard Error Format). One shape means a client
// writes one error path rather than one per endpoint.
type BadRequest = Error

// Conflict The error envelope for every non-2xx response, without exception
// (`docs/PLAN/05` Part B § Standard Error Format). One shape means a client
// writes one error path rather than one per endpoint.
type Conflict = Error

// Forbidden The error envelope for every non-2xx response, without exception
// (`docs/PLAN/05` Part B § Standard Error Format). One shape means a client
// writes one error path rather than one per endpoint.
type Forbidden = Error

// InternalError The error envelope for every non-2xx response, without exception
// (`docs/PLAN/05` Part B § Standard Error Format). One shape means a client
// writes one error path rather than one per endpoint.
type InternalError = Error

// NotFound The error envelope for every non-2xx response, without exception
// (`docs/PLAN/05` Part B § Standard Error Format). One shape means a client
// writes one error path rather than one per endpoint.
type NotFound = Error

// RateLimited The error envelope for every non-2xx response, without exception
// (`docs/PLAN/05` Part B § Standard Error Format). One shape means a client
// writes one error path rather than one per endpoint.
type RateLimited = Error

// Unauthorized The error envelope for every non-2xx response, without exception
// (`docs/PLAN/05` Part B § Standard Error Format). One shape means a client
// writes one error path rather than one per endpoint.
type Unauthorized = Error

// ListOrganizationsParams defines parameters for ListOrganizations.
type ListOrganizationsParams struct {
	// PageSize Maximum items to return. The server may return fewer, and returning
	// fewer never means the collection is exhausted — only an absent
	// `next_page_token` means that.
	PageSize *PageSize `form:"page_size,omitempty" json:"page_size,omitempty"`

	// PageToken The `next_page_token` from the previous response. Opaque: its contents
	// are not part of the contract and must not be constructed, parsed, or
	// persisted by a client.
	PageToken *PageToken `form:"page_token,omitempty" json:"page_token,omitempty"`
}

// CreateOrganizationParams defines parameters for CreateOrganization.
type CreateOrganizationParams struct {
	// IdempotencyKey A client-generated key making a retried `POST` safe. Replaying a
	// request with the same key returns the original result rather than
	// creating a second resource — which matters most for automated
	// provisioning, where a network timeout is indistinguishable from a
	// failure (`docs/PLAN/05` Part B).
	IdempotencyKey *IdempotencyKey `json:"Idempotency-Key,omitempty"`
}

// DeleteOrganizationParams defines parameters for DeleteOrganization.
type DeleteOrganizationParams struct {
	// ConfirmName The organization's current name, typed back. A mismatch is `400`.
	ConfirmName string `form:"confirm_name" json:"confirm_name"`

	// IdempotencyKey A client-generated key making a retried `POST` safe. Replaying a
	// request with the same key returns the original result rather than
	// creating a second resource — which matters most for automated
	// provisioning, where a network timeout is indistinguishable from a
	// failure (`docs/PLAN/05` Part B).
	IdempotencyKey *IdempotencyKey `json:"Idempotency-Key,omitempty"`
}

// CreateOrganizationJSONRequestBody defines body for CreateOrganization for application/json ContentType.
type CreateOrganizationJSONRequestBody = OrganizationCreate

// UpdateOrganizationJSONRequestBody defines body for UpdateOrganization for application/json ContentType.
type UpdateOrganizationJSONRequestBody = OrganizationUpdate

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// JSON Web Key Set
	// (GET /.well-known/jwks.json)
	GetJWKS(w http.ResponseWriter, r *http.Request)
	// OpenID Provider configuration
	// (GET /.well-known/openid-configuration)
	GetOpenIDConfiguration(w http.ResponseWriter, r *http.Request)
	// Liveness probe
	// (GET /healthz)
	GetLiveness(w http.ResponseWriter, r *http.Request)
	// Readiness probe
	// (GET /readyz)
	GetReadiness(w http.ResponseWriter, r *http.Request)
	// List organizations
	// (GET /v1/organizations)
	ListOrganizations(w http.ResponseWriter, r *http.Request, params ListOrganizationsParams)
	// Create an organization
	// (POST /v1/organizations)
	CreateOrganization(w http.ResponseWriter, r *http.Request, params CreateOrganizationParams)
	// Delete an organization
	// (DELETE /v1/organizations/{org_id})
	DeleteOrganization(w http.ResponseWriter, r *http.Request, orgId OrganizationId, params DeleteOrganizationParams)
	// Read an organization
	// (GET /v1/organizations/{org_id})
	GetOrganization(w http.ResponseWriter, r *http.Request, orgId OrganizationId)
	// Update an organization
	// (PATCH /v1/organizations/{org_id})
	UpdateOrganization(w http.ResponseWriter, r *http.Request, orgId OrganizationId)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// JSON Web Key Set
// (GET /.well-known/jwks.json)
func (_ Unimplemented) GetJWKS(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// OpenID Provider configuration
// (GET /.well-known/openid-configuration)
func (_ Unimplemented) GetOpenIDConfiguration(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Liveness probe
// (GET /healthz)
func (_ Unimplemented) GetLiveness(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Readiness probe
// (GET /readyz)
func (_ Unimplemented) GetReadiness(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List organizations
// (GET /v1/organizations)
func (_ Unimplemented) ListOrganizations(w http.ResponseWriter, r *http.Request, params ListOrganizationsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create an organization
// (POST /v1/organizations)
func (_ Unimplemented) CreateOrganization(w http.ResponseWriter, r *http.Request, params CreateOrganizationParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete an organization
// (DELETE /v1/organizations/{org_id})
func (_ Unimplemented) DeleteOrganization(w http.ResponseWriter, r *http.Request, orgId OrganizationId, params DeleteOrganizationParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Read an organization
// (GET /v1/organizations/{org_id})
func (_ Unimplemented) GetOrganization(w http.ResponseWriter, r *http.Request, orgId OrganizationId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update an organization
// (PATCH /v1/organizations/{org_id})
func (_ Unimplemented) UpdateOrganization(w http.ResponseWriter, r *http.Request, orgId OrganizationId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetJWKS operation middleware
func (siw *ServerInterfaceWrapper) GetJWKS(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetJWKS(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetOpenIDConfiguration operation middleware
func (siw *ServerInterfaceWrapper) GetOpenIDConfiguration(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetOpenIDConfiguration(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetLiveness operation middleware
func (siw *ServerInterfaceWrapper) GetLiveness(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetLiveness(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetReadiness operation middleware
func (siw *ServerInterfaceWrapper) GetReadiness(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetReadiness(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListOrganizations operation middleware
func (siw *ServerInterfaceWrapper) ListOrganizations(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, Oauth2Scopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListOrganizationsParams

	// ------------- Optional query parameter "page_size" -------------

	err = runtime.BindQueryParameter("form", true, false, "page_size", r.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page_size", Err: err})
		return
	}

	// ------------- Optional query parameter "page_token" -------------

	err = runtime.BindQueryParameter("form", true, false, "page_token", r.URL.Query(), &params.PageToken)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page_token", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListOrganizations(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateOrganization operation middleware
func (siw *ServerInterfaceWrapper) CreateOrganization(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, Oauth2Scopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateOrganizationParams

	headers := r.Header

	// ------------- Optional header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = &IdempotencyKey

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateOrganization(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteOrganization operation middleware
func (siw *ServerInterfaceWrapper) DeleteOrganization(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "org_id" -------------
	var orgId OrganizationId

	err = runtime.BindStyledParameterWithOptions("simple", "org_id", chi.URLParam(r, "org_id"), &orgId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "org_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, Oauth2Scopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params DeleteOrganizationParams

	// ------------- Required query parameter "confirm_name" -------------

	if paramValue := r.URL.Query().Get("confirm_name"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "confirm_name"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "confirm_name", r.URL.Query(), &params.ConfirmName)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "confirm_name", Err: err})
		return
	}

	headers := r.Header

	// ------------- Optional header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = &IdempotencyKey

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteOrganization(w, r, orgId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetOrganization operation middleware
func (siw *ServerInterfaceWrapper) GetOrganization(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "org_id" -------------
	var orgId OrganizationId

	err = runtime.BindStyledParameterWithOptions("simple", "org_id", chi.URLParam(r, "org_id"), &orgId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "org_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, Oauth2Scopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetOrganization(w, r, orgId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateOrganization operation middleware
func (siw *ServerInterfaceWrapper) UpdateOrganization(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "org_id" -------------
	var orgId OrganizationId

	err = runtime.BindStyledParameterWithOptions("simple", "org_id", chi.URLParam(r, "org_id"), &orgId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "org_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, Oauth2Scopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateOrganization(w, r, orgId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/.well-known/jwks.json", wrapper.GetJWKS)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/.well-known/openid-configuration", wrapper.GetOpenIDConfiguration)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/healthz", wrapper.GetLiveness)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/readyz", wrapper.GetReadiness)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/organizations", wrapper.ListOrganizations)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/organizations", wrapper.CreateOrganization)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/v1/organizations/{org_id}", wrapper.DeleteOrganization)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/organizations/{org_id}", wrapper.GetOrganization)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/v1/organizations/{org_id}", wrapper.UpdateOrganization)
	})

	return r
}

type BadRequestJSONResponse Error

type ConflictJSONResponse Error

type ForbiddenJSONResponse Error

type InternalErrorJSONResponse Error

type NotFoundJSONResponse Error

type RateLimitedResponseHeaders struct {
	RetryAfter          int
	XRateLimitLimit     int
	XRateLimitRemaining int
	XRateLimitReset     int
}
type RateLimitedJSONResponse struct {
	Body Error

	Headers RateLimitedResponseHeaders
}

type UnauthorizedJSONResponse Error

type GetJWKSRequestObject struct {
}

type GetJWKSResponseObject interface {
	VisitGetJWKSResponse(w http.ResponseWriter) error
}

type GetJWKS200ResponseHeaders struct {
	CacheControl string
}

type GetJWKS200ApplicationJwkSetPlusJSONResponse struct {
	Body    JWKS
	Headers GetJWKS200ResponseHeaders
}

func (response GetJWKS200ApplicationJwkSetPlusJSONResponse) VisitGetJWKSResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/jwk-set+json")
	w.Header().Set("Cache-Control", fmt.Sprint(response.Headers.CacheControl))
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response.Body)
}

type GetJWKS503JSONResponse Error

func (response GetJWKS503JSONResponse) VisitGetJWKSResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)

	return json.NewEncoder(w).Encode(response)
}

type GetOpenIDConfigurationRequestObject struct {
}

type GetOpenIDConfigurationResponseObject interface {
	VisitGetOpenIDConfigurationResponse(w http.ResponseWriter) error
}

type GetOpenIDConfiguration200ResponseHeaders struct {
	CacheControl string
}

type GetOpenIDConfiguration200JSONResponse struct {
	Body    OpenIDConfiguration
	Headers GetOpenIDConfiguration200ResponseHeaders
}

func (response GetOpenIDConfiguration200JSONResponse) VisitGetOpenIDConfigurationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("Cache-Control", fmt.Sprint(response.Headers.CacheControl))
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response.Body)
}

type GetLivenessRequestObject struct {
}

type GetLivenessResponseObject interface {
	VisitGetLivenessResponse(w http.ResponseWriter) error
}

type GetLiveness200JSONResponse LivenessStatus

func (response GetLiveness200JSONResponse) VisitGetLivenessResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetReadinessRequestObject struct {
}

type GetReadinessResponseObject interface {
	VisitGetReadinessResponse(w http.ResponseWriter) error
}

type GetReadiness200JSONResponse ReadinessStatus

func (response GetReadiness200JSONResponse) VisitGetReadinessResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetReadiness503JSONResponse ReadinessStatus

func (response GetReadiness503JSONResponse) VisitGetReadinessResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)

	return json.NewEncoder(w).Encode(response)
}

type ListOrganizationsRequestObject struct {
	Params ListOrganizationsParams
}

type ListOrganizationsResponseObject interface {
	VisitListOrganizationsResponse(w http.ResponseWriter) error
}

type ListOrganizations200JSONResponse OrganizationList

func (response ListOrganizations200JSONResponse) VisitListOrganizationsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListOrganizations400JSONResponse struct{ BadRequestJSONResponse }

func (response ListOrganizations400JSONResponse) VisitListOrganizationsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type ListOrganizations401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListOrganizations401JSONResponse) VisitListOrganizationsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type ListOrganizations403JSONResponse struct{ ForbiddenJSONResponse }

func (response ListOrganizations403JSONResponse) VisitListOrganizationsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type ListOrganizations429JSONResponse struct{ RateLimitedJSONResponse }

func (response ListOrganizations429JSONResponse) VisitListOrganizationsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("Retry-After", fmt.Sprint(response.Headers.RetryAfter))
	w.Header().Set("X-RateLimit-Limit", fmt.Sprint(response.Headers.XRateLimitLimit))
	w.Header().Set("X-RateLimit-Remaining", fmt.Sprint(response.Headers.XRateLimitRemaining))
	w.Header().Set("X-RateLimit-Reset", fmt.Sprint(response.Headers.XRateLimitReset))
	w.WriteHeader(429)

	return json.NewEncoder(w).Encode(response.Body)
}

type ListOrganizations500JSONResponse struct{ InternalErrorJSONResponse }

func (response ListOrganizations500JSONResponse) VisitListOrganizationsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type CreateOrganizationRequestObject struct {
	Params CreateOrganizationParams
	Body   *CreateOrganizationJSONRequestBody
}

type CreateOrganizationResponseObject interface {
	VisitCreateOrganizationResponse(w http.ResponseWriter) error
}

type CreateOrganization201JSONResponse Organization

func (response CreateOrganization201JSONResponse) VisitCreateOrganizationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateOrganization400JSONResponse struct{ BadRequestJSONResponse }

func (response CreateOrganization400JSONResponse) VisitCreateOrganizationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateOrganization401JSONResponse struct{ UnauthorizedJSONResponse }

func (response CreateOrganization401JSONResponse) VisitCreateOrganizationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type CreateOrganization403JSONResponse struct{ ForbiddenJSONResponse }

func (response CreateOrganization403JSONResponse) VisitCreateOrganizationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type CreateOrganization409JSONResponse struct{ ConflictJSONResponse }

func (response CreateOrganization409JSONResponse) VisitCreateOrganizationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type CreateOrganization429JSONResponse struct{ RateLimitedJSONResponse }

func (response CreateOrganization429JSONResponse) VisitCreateOrganizationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("Retry-After", fmt.Sprint(response.Headers.RetryAfter))
	w.Header().Set("X-RateLimit-Limit", fmt.Sprint(response.Headers.XRateLimitLimit))
	w.Header().Set("X-RateLimit-Remaining", fmt.Sprint(response.Headers.XRateLimitRemaining))
	w.Header().Set("X-RateLimit-Reset", fmt.Sprint(response.Headers.XRateLimitReset))
	w.WriteHeader(429)

	return json.NewEncoder(w).Encode(response.Body)
}

type CreateOrganization500JSONResponse struct{ InternalErrorJSONResponse }

func (response CreateOrganization500JSONResponse) VisitCreateOrganizationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type DeleteOrganizationRequestObject struct {
	OrgId  OrganizationId `json:"org_id"`
	Params DeleteOrganizationParams
}

type DeleteOrganizationResponseObject interface {
	VisitDeleteOrganizationResponse(w http.ResponseWriter) error
}

type DeleteOrganization204Response struct {
}

func (response DeleteOrganization204Response) VisitDeleteOrganizationResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteOrganization400JSONResponse struct{ BadRequestJSONResponse }

func (response DeleteOrganization400JSONResponse) VisitDeleteOrganizationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type DeleteOrganization401JSONResponse struct{ UnauthorizedJSONResponse }

func (response DeleteOrganization401JSONResponse) VisitDeleteOrganizationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type DeleteOrganization403JSONResponse struct{ ForbiddenJSONResponse }

func (response DeleteOrganization403JSONResponse) VisitDeleteOrganizationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type DeleteOrganization404JSONResponse struct{ NotFoundJSONResponse }

func (response DeleteOrganization404JSONResponse) VisitDeleteOrganizationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type DeleteOrganization429JSONResponse struct{ RateLimitedJSONResponse }

func (response DeleteOrganization429JSONResponse) VisitDeleteOrganizationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("Retry-After", fmt.Sprint(response.Headers.RetryAfter))
	w.Header().Set("X-RateLimit-Limit", fmt.Sprint(response.Headers.XRateLimitLimit))
	w.Header().Set("X-RateLimit-Remaining", fmt.Sprint(response.Headers.XRateLimitRemaining))
	w.Header().Set("X-RateLimit-Reset", fmt.Sprint(response.Headers.XRateLimitReset))
	w.WriteHeader(429)

	return json.NewEncoder(w).Encode(response.Body)
}

type DeleteOrganization500JSONResponse struct{ InternalErrorJSONResponse }

func (response DeleteOrganization500JSONResponse) VisitDeleteOrganizationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetOrganizationRequestObject struct {
	OrgId OrganizationId `json:"org_id"`
}

type GetOrganizationResponseObject interface {
	VisitGetOrganizationResponse(w http.ResponseWriter) error
}

type GetOrganization200JSONResponse Organization

func (response GetOrganization200JSONResponse) VisitGetOrganizationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetOrganization401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetOrganization401JSONResponse) VisitGetOrganizationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetOrganization403JSONResponse struct{ ForbiddenJSONResponse }

func (response GetOrganization403JSONResponse) VisitGetOrganizationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type GetOrganization404JSONResponse struct{ NotFoundJSONResponse }

func (response GetOrganization404JSONResponse) VisitGetOrganizationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetOrganization429JSONResponse struct{ RateLimitedJSONResponse }

func (response GetOrganization429JSONResponse) VisitGetOrganizationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("Retry-After", fmt.Sprint(response.Headers.RetryAfter))
	w.Header().Set("X-RateLimit-Limit", fmt.Sprint(response.Headers.XRateLimitLimit))
	w.Header().Set("X-RateLimit-Remaining", fmt.Sprint(response.Headers.XRateLimitRemaining))
	w.Header().Set("X-RateLimit-Reset", fmt.Sprint(response.Headers.XRateLimitReset))
	w.WriteHeader(429)

	return json.NewEncoder(w).Encode(response.Body)
}

type GetOrganization500JSONResponse struct{ InternalErrorJSONResponse }

func (response GetOrganization500JSONResponse) VisitGetOrganizationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type UpdateOrganizationRequestObject struct {
	OrgId OrganizationId `json:"org_id"`
	Body  *UpdateOrganizationJSONRequestBody
}

type UpdateOrganizationResponseObject interface {
	VisitUpdateOrganizationResponse(w http.ResponseWriter) error
}

type UpdateOrganization200JSONResponse Organization

func (response UpdateOrganization200JSONResponse) VisitUpdateOrganizationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UpdateOrganization400JSONResponse struct{ BadRequestJSONResponse }

func (response UpdateOrganization400JSONResponse) VisitUpdateOrganizationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type UpdateOrganization401JSONResponse struct{ UnauthorizedJSONResponse }

func (response UpdateOrganization401JSONResponse) VisitUpdateOrganizationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type UpdateOrganization403JSONResponse struct{ ForbiddenJSONResponse }

func (response UpdateOrganization403JSONResponse) VisitUpdateOrganizationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type UpdateOrganization404JSONResponse struct{ NotFoundJSONResponse }

func (response UpdateOrganization404JSONResponse) VisitUpdateOrganizationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type UpdateOrganization409JSONResponse struct{ ConflictJSONResponse }

func (response UpdateOrganization409JSONResponse) VisitUpdateOrganizationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type UpdateOrganization429JSONResponse struct{ RateLimitedJSONResponse }

func (response UpdateOrganization429JSONResponse) VisitUpdateOrganizationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("Retry-After", fmt.Sprint(response.Headers.RetryAfter))
	w.Header().Set("X-RateLimit-Limit", fmt.Sprint(response.Headers.XRateLimitLimit))
	w.Header().Set("X-RateLimit-Remaining", fmt.Sprint(response.Headers.XRateLimitRemaining))
	w.Header().Set("X-RateLimit-Reset", fmt.Sprint(response.Headers.XRateLimitReset))
	w.WriteHeader(429)

	return json.NewEncoder(w).Encode(response.Body)
}

type UpdateOrganization500JSONResponse struct{ InternalErrorJSONResponse }

func (response UpdateOrganization500JSONResponse) VisitUpdateOrganizationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// JSON Web Key Set
	// (GET /.well-known/jwks.json)
	GetJWKS(ctx context.Context, request GetJWKSRequestObject) (GetJWKSResponseObject, error)
	// OpenID Provider configuration
	// (GET /.well-known/openid-configuration)
	GetOpenIDConfiguration(ctx context.Context, request GetOpenIDConfigurationRequestObject) (GetOpenIDConfigurationResponseObject, error)
	// Liveness probe
	// (GET /healthz)
	GetLiveness(ctx context.Context, request GetLivenessRequestObject) (GetLivenessResponseObject, error)
	// Readiness probe
	// (GET /readyz)
	GetReadiness(ctx context.Context, request GetReadinessRequestObject) (GetReadinessResponseObject, error)
	// List organizations
	// (GET /v1/organizations)
	ListOrganizations(ctx context.Context, request ListOrganizationsRequestObject) (ListOrganizationsResponseObject, error)
	// Create an organization
	// (POST /v1/organizations)
	CreateOrganization(ctx context.Context, request CreateOrganizationRequestObject) (CreateOrganizationResponseObject, error)
	// Delete an organization
	// (DELETE /v1/organizations/{org_id})
	DeleteOrganization(ctx context.Context, request DeleteOrganizationRequestObject) (DeleteOrganizationResponseObject, error)
	// Read an organization
	// (GET /v1/organizations/{org_id})
	GetOrganization(ctx context.Context, request GetOrganizationRequestObject) (GetOrganizationResponseObject, error)
	// Update an organization
	// (PATCH /v1/organizations/{org_id})
	UpdateOrganization(ctx context.Context, request UpdateOrganizationRequestObject) (UpdateOrganizationResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetJWKS operation middleware
func (sh *strictHandler) GetJWKS(w http.ResponseWriter, r *http.Request) {
	var request GetJWKSRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetJWKS(ctx, request.(GetJWKSRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetJWKS")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetJWKSResponseObject); ok {
		if err := validResponse.VisitGetJWKSResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetOpenIDConfiguration operation middleware
func (sh *strictHandler) GetOpenIDConfiguration(w http.ResponseWriter, r *http.Request) {
	var request GetOpenIDConfigurationRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetOpenIDConfiguration(ctx, request.(GetOpenIDConfigurationRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetOpenIDConfiguration")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetOpenIDConfigurationResponseObject); ok {
		if err := validResponse.VisitGetOpenIDConfigurationResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetLiveness operation middleware
func (sh *strictHandler) GetLiveness(w http.ResponseWriter, r *http.Request) {
	var request GetLivenessRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetLiveness(ctx, request.(GetLivenessRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetLiveness")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetLivenessResponseObject); ok {
		if err := validResponse.VisitGetLivenessResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetReadiness operation middleware
func (sh *strictHandler) GetReadiness(w http.ResponseWriter, r *http.Request) {
	var request GetReadinessRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetReadiness(ctx, request.(GetReadinessRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetReadiness")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetReadinessResponseObject); ok {
		if err := validResponse.VisitGetReadinessResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListOrganizations operation middleware
func (sh *strictHandler) ListOrganizations(w http.ResponseWriter, r *http.Request, params ListOrganizationsParams) {
	var request ListOrganizationsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListOrganizations(ctx, request.(ListOrganizationsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListOrganizations")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListOrganizationsResponseObject); ok {
		if err := validResponse.VisitListOrganizationsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateOrganization operation middleware
func (sh *strictHandler) CreateOrganization(w http.ResponseWriter, r *http.Request, params CreateOrganizationParams) {
	var request CreateOrganizationRequestObject

	request.Params = params

	var body CreateOrganizationJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateOrganization(ctx, request.(CreateOrganizationRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateOrganization")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateOrganizationResponseObject); ok {
		if err := validResponse.VisitCreateOrganizationResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteOrganization operation middleware
func (sh *strictHandler) DeleteOrganization(w http.ResponseWriter, r *http.Request, orgId OrganizationId, params DeleteOrganizationParams) {
	var request DeleteOrganizationRequestObject

	request.OrgId = orgId
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteOrganization(ctx, request.(DeleteOrganizationRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteOrganization")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteOrganizationResponseObject); ok {
		if err := validResponse.VisitDeleteOrganizationResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetOrganization operation middleware
func (sh *strictHandler) GetOrganization(w http.ResponseWriter, r *http.Request, orgId OrganizationId) {
	var request GetOrganizationRequestObject

	request.OrgId = orgId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetOrganization(ctx, request.(GetOrganizationRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetOrganization")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetOrganizationResponseObject); ok {
		if err := validResponse.VisitGetOrganizationResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateOrganization operation middleware
func (sh *strictHandler) UpdateOrganization(w http.ResponseWriter, r *http.Request, orgId OrganizationId) {
	var request UpdateOrganizationRequestObject

	request.OrgId = orgId

	var body UpdateOrganizationJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateOrganization(ctx, request.(UpdateOrganizationRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateOrganization")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateOrganizationResponseObject); ok {
		if err := validResponse.VisitUpdateOrganizationResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
