// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/go-chi/chi/v5"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ErrorCode.
const (
	CONFLICT         ErrorCode = "CONFLICT"
	INTERNAL         ErrorCode = "INTERNAL"
	NOTFOUND         ErrorCode = "NOT_FOUND"
	PERMISSIONDENIED ErrorCode = "PERMISSION_DENIED"
	RATELIMITED      ErrorCode = "RATE_LIMITED"
	UNAUTHENTICATED  ErrorCode = "UNAUTHENTICATED"
	VALIDATIONERROR  ErrorCode = "VALIDATION_ERROR"
)

// Defines values for LivenessStatusStatus.
const (
	Ok LivenessStatusStatus = "ok"
)

// Defines values for OAuthErrorError.
const (
	InvalidClient        OAuthErrorError = "invalid_client"
	InvalidGrant         OAuthErrorError = "invalid_grant"
	InvalidRequest       OAuthErrorError = "invalid_request"
	InvalidScope         OAuthErrorError = "invalid_scope"
	ServerError          OAuthErrorError = "server_error"
	UnauthorizedClient   OAuthErrorError = "unauthorized_client"
	UnsupportedGrantType OAuthErrorError = "unsupported_grant_type"
)

// Defines values for ReadinessStatusStatus.
const (
	Ready       ReadinessStatusStatus = "ready"
	Unavailable ReadinessStatusStatus = "unavailable"
)

// Defines values for TokenResponseTokenType.
const (
	Bearer TokenResponseTokenType = "Bearer"
)

// Error The error envelope for every non-2xx response, without exception
// (`docs/PLAN/05` Part B § Standard Error Format). One shape means a client
// writes one error path rather than one per endpoint.
type Error struct {
	Error struct {
		// Code A stable, machine-readable code. Clients branch on this; `message` is
		// for humans and may be reworded at any time without a version bump.
		//
		// Deliberately coarse. A code per failure mode leaks internal structure
		// and becomes an enumeration oracle — `USER_NOT_FOUND` versus
		// `PERMISSION_DENIED` tells an attacker which addresses are registered
		// (`docs/SECURITY/02` §12).
		Code ErrorCode `json:"code"`

		// Details Field-level problems. Omitted when there are none.
		Details *[]ErrorDetail `json:"details,omitempty"`

		// Message Human-readable, safe to surface in a UI, and never containing a
		// token, a password, a raw `/v1/authz/check` resource attribute,
		// a stack trace, or a SQL fragment (`docs/PLAN/13`, `CLAUDE.md`).
		Message string `json:"message"`
	} `json:"error"`
}

// ErrorCode A stable, machine-readable code. Clients branch on this; `message` is
// for humans and may be reworded at any time without a version bump.
//
// Deliberately coarse. A code per failure mode leaks internal structure
// and becomes an enumeration oracle — `USER_NOT_FOUND` versus
// `PERMISSION_DENIED` tells an attacker which addresses are registered
// (`docs/SECURITY/02` §12).
type ErrorCode string

// ErrorDetail One specific problem within a failed request. Present for
// `VALIDATION_ERROR`, where naming the bad field is helpful and discloses
// nothing the caller did not send. Generally absent otherwise.
type ErrorDetail struct {
	// Field JSON path to the offending field, relative to the request body.
	Field string `json:"field"`

	// Issue What is wrong with it, in plain language.
	Issue string `json:"issue"`
}

// JWK One public key, per RFC 7517. Private parameters (`d`, `p`, `q`, `dp`,
// `dq`, `qi`) never appear.
type JWK struct {
	Alg *string `json:"alg,omitempty"`

	// Crv EC curve, for ES256 keys.
	Crv *string `json:"crv,omitempty"`

	// E RSA public exponent, base64url.
	E *string `json:"e,omitempty"`

	// Kid An RFC 7638 thumbprint of the key, so it is stable across restarts
	// and cannot be chosen by anyone.
	Kid string `json:"kid"`
	Kty string `json:"kty"`

	// N RSA modulus, base64url.
	N   *string `json:"n,omitempty"`
	Use string  `json:"use"`
	X   *string `json:"x,omitempty"`
	Y   *string `json:"y,omitempty"`
}

// JWKS defines model for JWKS.
type JWKS struct {
	Keys []JWK `json:"keys"`
}

// LivenessStatus The complete `/healthz` response. There are no other fields, and none
// will be added that name a dependency or a version.
type LivenessStatus struct {
	Status LivenessStatusStatus `json:"status"`
}

// LivenessStatusStatus defines model for LivenessStatus.Status.
type LivenessStatusStatus string

// OAuthError OAuth 2.1's error shape (RFC 6749 § 5.2), used by the protocol
// endpoints. Distinct from the `Error` envelope every other endpoint
// returns, because this is what a consumer's OAuth library parses.
type OAuthError struct {
	Error OAuthErrorError `json:"error"`

	// ErrorDescription Human-readable, and deliberately terse about specifics. It names
	// what was wrong, never what the correct value would have been.
	ErrorDescription *string `json:"error_description,omitempty"`
}

// OAuthErrorError defines model for OAuthError.Error.
type OAuthErrorError string

// OpenIDConfiguration OpenID Provider metadata. Fields for unimplemented endpoints are
// omitted rather than emitted empty.
type OpenIDConfiguration struct {
	// AuthorizationEndpoint Present once the authorization endpoint exists.
	AuthorizationEndpoint *string   `json:"authorization_endpoint,omitempty"`
	ClaimsSupported       *[]string `json:"claims_supported,omitempty"`

	// CodeChallengeMethodsSupported `S256` only. Never `plain`.
	CodeChallengeMethodsSupported *[]string `json:"code_challenge_methods_supported,omitempty"`
	EndSessionEndpoint            *string   `json:"end_session_endpoint,omitempty"`

	// GrantTypesSupported Never contains `implicit` or `password`: both are ruled out
	// permanently by `docs/PLAN/05` § Supported Grant Types, and advertising
	// a grant this service refuses invites a client to build against it.
	GrantTypesSupported              *[]string `json:"grant_types_supported,omitempty"`
	IdTokenSigningAlgValuesSupported []string  `json:"id_token_signing_alg_values_supported"`
	IntrospectionEndpoint            *string   `json:"introspection_endpoint,omitempty"`

	// Issuer The identifier clients validate the `iss` claim against. Compared
	// byte for byte, so it never carries a trailing slash.
	Issuer                 string    `json:"issuer"`
	JwksUri                string    `json:"jwks_uri"`
	ResponseTypesSupported *[]string `json:"response_types_supported,omitempty"`
	RevocationEndpoint     *string   `json:"revocation_endpoint,omitempty"`
	ScopesSupported        *[]string `json:"scopes_supported,omitempty"`

	// SubjectTypesSupported `public` only. Pairwise identifiers are a privacy feature this
	// service does not implement.
	SubjectTypesSupported []string `json:"subject_types_supported"`

	// TokenEndpoint Present once the token endpoint exists.
	TokenEndpoint    *string `json:"token_endpoint,omitempty"`
	UserinfoEndpoint *string `json:"userinfo_endpoint,omitempty"`
}

// PageInfo The pagination envelope every collection response embeds.
//
// Token-based rather than offset-based: an offset re-reads rows that
// shifted under concurrent writes, silently skipping or duplicating
// entries. For an audit log or a user list that is a correctness bug that
// nobody notices.
type PageInfo struct {
	// NextPageToken Pass as `page_token` for the following page. **Absent when there
	// are no more results** — the presence of this field is the only
	// valid end-of-collection test. An empty array is not one: a page can
	// legitimately return zero items and still have a next page.
	NextPageToken *string `json:"next_page_token,omitempty"`
}

// ReadinessStatus The complete `/readyz` response.
//
// Note that the ready value is `ready`, not `ok`. The two probes report
// different vocabularies, which was found by writing this spec against
// the running code rather than from memory. It is recorded accurately
// rather than tidied, because a client already parsing `ready` would
// break if the server were changed to match a prettier spec — the spec
// describes what ships (ADR-013).
type ReadinessStatus struct {
	Status ReadinessStatusStatus `json:"status"`
}

// ReadinessStatusStatus defines model for ReadinessStatus.Status.
type ReadinessStatusStatus string

// ResourceId A prefixed, sortable identifier — `usr_`, `org_`, `prj_`, `app_`,
// `rol_`, `grt_`. The prefix makes an identifier pasted into a support
// ticket self-describing, and makes passing a project id where a user id
// belongs visible on sight rather than at the database.
type ResourceId = string

// TokenResponse A successful token response (RFC 6749 § 5.1).
type TokenResponse struct {
	// AccessToken A JWT with `typ: at+jwt`. Verify it against the JWKS at
	// `/.well-known/jwks.json` and check `aud` against yourself.
	AccessToken string `json:"access_token"`

	// ExpiresIn Seconds until the access token expires.
	ExpiresIn int `json:"expires_in"`

	// IdToken Present when the `openid` scope was granted and a user
	// authenticated. Absent on a refresh: nothing was authenticated just
	// now, and an assertion that one had been would be a false statement
	// with a fresh timestamp on it.
	IdToken *string `json:"id_token,omitempty"`

	// RefreshToken Present when the `offline_access` scope was granted. Opaque, not a
	// JWT — it must be revocable, which a stateless token cannot be.
	RefreshToken *string `json:"refresh_token,omitempty"`

	// Scope The granted scope, space-delimited.
	Scope     *string                `json:"scope,omitempty"`
	TokenType TokenResponseTokenType `json:"token_type"`
}

// TokenResponseTokenType defines model for TokenResponse.TokenType.
type TokenResponseTokenType string

// UserInfo The claims the presented access token's scopes authorise.
//
// Only `sub` is guaranteed. Every other property appears when its scope
// was granted AND the underlying value is set — an absent claim means the
// value is not known or not authorised, and the two are deliberately not
// distinguished.
type UserInfo struct {
	// Email Requires the `email` scope. `email_verified` is deliberately not
	// returned: nothing in this service verifies an address yet, and
	// asserting `false` would claim a check that never happened.
	Email *openapi_types.Email `json:"email,omitempty"`

	// Name Display name. Requires the `profile` scope.
	Name *string `json:"name,omitempty"`

	// PreferredUsername Requires the `profile` scope. A user may change it, so it is not
	// an identifier — use `sub`.
	PreferredUsername *string `json:"preferred_username,omitempty"`

	// Sub The user's stable identifier. Not sequential, not guessable, and
	// never the email address — store this as the user's permanent key.
	Sub openapi_types.UUID `json:"sub"`

	// UpdatedAt Seconds since the epoch, when the user record last changed
	// (OIDC Core 5.1). Requires the `profile` scope.
	UpdatedAt *int64 `json:"updated_at,omitempty"`
}

// IdempotencyKey defines model for IdempotencyKey.
type IdempotencyKey = string

// OrganizationId A prefixed, sortable identifier — `usr_`, `org_`, `prj_`, `app_`,
// `rol_`, `grt_`. The prefix makes an identifier pasted into a support
// ticket self-describing, and makes passing a project id where a user id
// belongs visible on sight rather than at the database.
type OrganizationId = ResourceId

// PageSize defines model for PageSize.
type PageSize = int

// PageToken defines model for PageToken.
type PageToken = string

// BadRequest The error envelope for every non-2xx response, without exception
// (`docs/PLAN/05` Part B § Standard Error Format). One shape means a client
// writes one error path rather than one per endpoint.
type BadRequest = Error

// Conflict The error envelope for every non-2xx response, without exception
// (`docs/PLAN/05` Part B § Standard Error Format). One shape means a client
// writes one error path rather than one per endpoint.
type Conflict = Error

// Forbidden The error envelope for every non-2xx response, without exception
// (`docs/PLAN/05` Part B § Standard Error Format). One shape means a client
// writes one error path rather than one per endpoint.
type Forbidden = Error

// InternalError The error envelope for every non-2xx response, without exception
// (`docs/PLAN/05` Part B § Standard Error Format). One shape means a client
// writes one error path rather than one per endpoint.
type InternalError = Error

// NotFound The error envelope for every non-2xx response, without exception
// (`docs/PLAN/05` Part B § Standard Error Format). One shape means a client
// writes one error path rather than one per endpoint.
type NotFound = Error

// RateLimited The error envelope for every non-2xx response, without exception
// (`docs/PLAN/05` Part B § Standard Error Format). One shape means a client
// writes one error path rather than one per endpoint.
type RateLimited = Error

// Unauthorized The error envelope for every non-2xx response, without exception
// (`docs/PLAN/05` Part B § Standard Error Format). One shape means a client
// writes one error path rather than one per endpoint.
type Unauthorized = Error

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// JSON Web Key Set
	// (GET /.well-known/jwks.json)
	GetJWKS(w http.ResponseWriter, r *http.Request)
	// OpenID Provider configuration
	// (GET /.well-known/openid-configuration)
	GetOpenIDConfiguration(w http.ResponseWriter, r *http.Request)
	// Liveness probe
	// (GET /healthz)
	GetLiveness(w http.ResponseWriter, r *http.Request)
	// Readiness probe
	// (GET /readyz)
	GetReadiness(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// JSON Web Key Set
// (GET /.well-known/jwks.json)
func (_ Unimplemented) GetJWKS(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// OpenID Provider configuration
// (GET /.well-known/openid-configuration)
func (_ Unimplemented) GetOpenIDConfiguration(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Liveness probe
// (GET /healthz)
func (_ Unimplemented) GetLiveness(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Readiness probe
// (GET /readyz)
func (_ Unimplemented) GetReadiness(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetJWKS operation middleware
func (siw *ServerInterfaceWrapper) GetJWKS(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetJWKS(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetOpenIDConfiguration operation middleware
func (siw *ServerInterfaceWrapper) GetOpenIDConfiguration(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetOpenIDConfiguration(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetLiveness operation middleware
func (siw *ServerInterfaceWrapper) GetLiveness(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetLiveness(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetReadiness operation middleware
func (siw *ServerInterfaceWrapper) GetReadiness(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetReadiness(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/.well-known/jwks.json", wrapper.GetJWKS)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/.well-known/openid-configuration", wrapper.GetOpenIDConfiguration)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/healthz", wrapper.GetLiveness)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/readyz", wrapper.GetReadiness)
	})

	return r
}

type BadRequestJSONResponse Error

type ConflictJSONResponse Error

type ForbiddenJSONResponse Error

type InternalErrorJSONResponse Error

type NotFoundJSONResponse Error

type RateLimitedResponseHeaders struct {
	RetryAfter          int
	XRateLimitLimit     int
	XRateLimitRemaining int
	XRateLimitReset     int
}
type RateLimitedJSONResponse struct {
	Body Error

	Headers RateLimitedResponseHeaders
}

type UnauthorizedJSONResponse Error

type GetJWKSRequestObject struct {
}

type GetJWKSResponseObject interface {
	VisitGetJWKSResponse(w http.ResponseWriter) error
}

type GetJWKS200ResponseHeaders struct {
	CacheControl string
}

type GetJWKS200ApplicationJwkSetPlusJSONResponse struct {
	Body    JWKS
	Headers GetJWKS200ResponseHeaders
}

func (response GetJWKS200ApplicationJwkSetPlusJSONResponse) VisitGetJWKSResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/jwk-set+json")
	w.Header().Set("Cache-Control", fmt.Sprint(response.Headers.CacheControl))
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response.Body)
}

type GetJWKS503JSONResponse Error

func (response GetJWKS503JSONResponse) VisitGetJWKSResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)

	return json.NewEncoder(w).Encode(response)
}

type GetOpenIDConfigurationRequestObject struct {
}

type GetOpenIDConfigurationResponseObject interface {
	VisitGetOpenIDConfigurationResponse(w http.ResponseWriter) error
}

type GetOpenIDConfiguration200ResponseHeaders struct {
	CacheControl string
}

type GetOpenIDConfiguration200JSONResponse struct {
	Body    OpenIDConfiguration
	Headers GetOpenIDConfiguration200ResponseHeaders
}

func (response GetOpenIDConfiguration200JSONResponse) VisitGetOpenIDConfigurationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("Cache-Control", fmt.Sprint(response.Headers.CacheControl))
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response.Body)
}

type GetLivenessRequestObject struct {
}

type GetLivenessResponseObject interface {
	VisitGetLivenessResponse(w http.ResponseWriter) error
}

type GetLiveness200JSONResponse LivenessStatus

func (response GetLiveness200JSONResponse) VisitGetLivenessResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetReadinessRequestObject struct {
}

type GetReadinessResponseObject interface {
	VisitGetReadinessResponse(w http.ResponseWriter) error
}

type GetReadiness200JSONResponse ReadinessStatus

func (response GetReadiness200JSONResponse) VisitGetReadinessResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetReadiness503JSONResponse ReadinessStatus

func (response GetReadiness503JSONResponse) VisitGetReadinessResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// JSON Web Key Set
	// (GET /.well-known/jwks.json)
	GetJWKS(ctx context.Context, request GetJWKSRequestObject) (GetJWKSResponseObject, error)
	// OpenID Provider configuration
	// (GET /.well-known/openid-configuration)
	GetOpenIDConfiguration(ctx context.Context, request GetOpenIDConfigurationRequestObject) (GetOpenIDConfigurationResponseObject, error)
	// Liveness probe
	// (GET /healthz)
	GetLiveness(ctx context.Context, request GetLivenessRequestObject) (GetLivenessResponseObject, error)
	// Readiness probe
	// (GET /readyz)
	GetReadiness(ctx context.Context, request GetReadinessRequestObject) (GetReadinessResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetJWKS operation middleware
func (sh *strictHandler) GetJWKS(w http.ResponseWriter, r *http.Request) {
	var request GetJWKSRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetJWKS(ctx, request.(GetJWKSRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetJWKS")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetJWKSResponseObject); ok {
		if err := validResponse.VisitGetJWKSResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetOpenIDConfiguration operation middleware
func (sh *strictHandler) GetOpenIDConfiguration(w http.ResponseWriter, r *http.Request) {
	var request GetOpenIDConfigurationRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetOpenIDConfiguration(ctx, request.(GetOpenIDConfigurationRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetOpenIDConfiguration")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetOpenIDConfigurationResponseObject); ok {
		if err := validResponse.VisitGetOpenIDConfigurationResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetLiveness operation middleware
func (sh *strictHandler) GetLiveness(w http.ResponseWriter, r *http.Request) {
	var request GetLivenessRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetLiveness(ctx, request.(GetLivenessRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetLiveness")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetLivenessResponseObject); ok {
		if err := validResponse.VisitGetLivenessResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetReadiness operation middleware
func (sh *strictHandler) GetReadiness(w http.ResponseWriter, r *http.Request) {
	var request GetReadinessRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetReadiness(ctx, request.(GetReadinessRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetReadiness")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetReadinessResponseObject); ok {
		if err := validResponse.VisitGetReadinessResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
