/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe
         * @description Answers whether the process is running. It performs no dependency
         *     checks and cannot fail while the process is able to respond at all.
         *
         *     The distinction from `/readyz` is load-bearing. A liveness probe that
         *     checks the database restarts the service during a database outage,
         *     which converts a recoverable dependency failure into a crash loop that
         *     prevents recovery (`PLAN/14`).
         */
        get: operations["getLiveness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness probe
         * @description Answers whether the process can serve traffic right now, which includes
         *     its dependencies being reachable.
         *
         *     A failure removes this instance from the load balancer without
         *     restarting it — the correct response to a dependency being briefly
         *     unavailable.
         */
        get: operations["getReadiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description The complete `/healthz` response. There are no other fields, and none
         *     will be added that name a dependency or a version.
         */
        LivenessStatus: {
            /** @enum {string} */
            status: "ok";
        };
        /**
         * @description The complete `/readyz` response.
         *
         *     Note that the ready value is `ready`, not `ok`. The two probes report
         *     different vocabularies, which was found by writing this spec against
         *     the running code rather than from memory. It is recorded accurately
         *     rather than tidied, because a client already parsing `ready` would
         *     break if the server were changed to match a prettier spec — the spec
         *     describes what ships (ADR-013).
         */
        ReadinessStatus: {
            /** @enum {string} */
            status: "ready" | "unavailable";
        };
        /**
         * @description A prefixed, sortable identifier — `usr_`, `org_`, `prj_`, `app_`,
         *     `rol_`, `grt_`. The prefix makes an identifier pasted into a support
         *     ticket self-describing, and makes passing a project id where a user id
         *     belongs visible on sight rather than at the database.
         * @example usr_01HQZX3M8K4N7P2R5T9V6W8Y0B
         */
        ResourceId: string;
        /**
         * @description A stable, machine-readable code. Clients branch on this; `message` is
         *     for humans and may be reworded at any time without a version bump.
         *
         *     Deliberately coarse. A code per failure mode leaks internal structure
         *     and becomes an enumeration oracle — `USER_NOT_FOUND` versus
         *     `PERMISSION_DENIED` tells an attacker which addresses are registered
         *     (`SECURITY/02` §12).
         * @enum {string}
         */
        ErrorCode: "VALIDATION_ERROR" | "UNAUTHENTICATED" | "PERMISSION_DENIED" | "NOT_FOUND" | "CONFLICT" | "RATE_LIMITED" | "INTERNAL";
        /**
         * @description One specific problem within a failed request. Present for
         *     `VALIDATION_ERROR`, where naming the bad field is helpful and discloses
         *     nothing the caller did not send. Generally absent otherwise.
         */
        ErrorDetail: {
            /**
             * @description JSON path to the offending field, relative to the request body.
             * @example email
             */
            field: string;
            /**
             * @description What is wrong with it, in plain language.
             * @example email format is not valid
             */
            issue: string;
        };
        /**
         * @description The error envelope for every non-2xx response, without exception
         *     (`PLAN/05` Part B § Standard Error Format). One shape means a client
         *     writes one error path rather than one per endpoint.
         */
        Error: {
            error: {
                code: components["schemas"]["ErrorCode"];
                /**
                 * @description Human-readable, safe to surface in a UI, and never containing a
                 *     token, a password, a raw `/v1/authz/check` resource attribute,
                 *     a stack trace, or a SQL fragment (`PLAN/13`, `CLAUDE.md`).
                 */
                message: string;
                /** @description Field-level problems. Omitted when there are none. */
                details?: components["schemas"]["ErrorDetail"][];
            };
        };
        /**
         * @description The pagination envelope every collection response embeds.
         *
         *     Token-based rather than offset-based: an offset re-reads rows that
         *     shifted under concurrent writes, silently skipping or duplicating
         *     entries. For an audit log or a user list that is a correctness bug that
         *     nobody notices.
         */
        PageInfo: {
            /**
             * @description Pass as `page_token` for the following page. **Absent when there
             *     are no more results** — the presence of this field is the only
             *     valid end-of-collection test. An empty array is not one: a page can
             *     legitimately return zero items and still have a next page.
             */
            next_page_token?: string;
        };
    };
    responses: {
        /** @description The request is malformed or fails validation. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description No access token, or one that is expired, malformed, or revoked. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /**
         * @description Authenticated, but not permitted. Returned for a resource in another
         *     organization even when it exists — distinguishing "forbidden" from "not
         *     found" across a tenant boundary confirms the resource's existence to
         *     someone with no right to know it (`PLAN/08`, `SECURITY/02` §3).
         */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description No such resource, or none visible to this caller. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The request conflicts with the current state, such as a duplicate email. */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /**
         * @description Too many requests. Limits are applied per `client_id` or API key rather
         *     than per IP, so one noisy tenant behind a shared NAT cannot exhaust
         *     another's budget (`PLAN/05` Part B).
         */
        RateLimited: {
            headers: {
                /** @description Requests permitted in the current window. */
                "X-RateLimit-Limit"?: number;
                /** @description Requests left in the current window. */
                "X-RateLimit-Remaining"?: number;
                /** @description Unix seconds at which the window resets. */
                "X-RateLimit-Reset"?: number;
                /** @description Seconds to wait before retrying. */
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /**
         * @description An unexpected failure. The message is deliberately generic; the detail
         *     is correlated by request id in the logs.
         */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /**
         * @description Maximum items to return. The server may return fewer, and returning
         *     fewer never means the collection is exhausted — only an absent
         *     `next_page_token` means that.
         */
        PageSize: number;
        /**
         * @description The `next_page_token` from the previous response. Opaque: its contents
         *     are not part of the contract and must not be constructed, parsed, or
         *     persisted by a client.
         */
        PageToken: string;
        /** @description The organization that owns the resource. Every request is scoped to exactly one. */
        OrganizationId: components["schemas"]["ResourceId"];
        /**
         * @description A client-generated key making a retried `POST` safe. Replaying a
         *     request with the same key returns the original result rather than
         *     creating a second resource — which matters most for automated
         *     provisioning, where a network timeout is indistinguishable from a
         *     failure (`PLAN/05` Part B).
         */
        IdempotencyKey: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getLiveness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The process is alive. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LivenessStatus"];
                };
            };
        };
    };
    getReadiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ready to serve traffic. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessStatus"];
                };
            };
            /**
             * @description Not ready. The body names no dependency and gives no detail, on
             *     purpose: this endpoint is reachable from the public ingress, and
             *     "which of our dependencies is down" is not something to tell an
             *     anonymous caller. The detail is in the logs and metrics.
             */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessStatus"];
                };
            };
        };
    };
}
