/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/.well-known/openid-configuration": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * OpenID Provider configuration
         * @description The discovery document, per OpenID Connect Discovery 1.0. Point a
         *     conforming client library at this URL instead of copying endpoint
         *     values into its configuration by hand.
         *
         *     **It lists only what is implemented.** The authorization and token
         *     endpoints arrive in later phases and are absent until they exist —
         *     the document is rendered from the service's registered capabilities,
         *     so it cannot advertise an endpoint that would return 404.
         *
         *     `code_challenge_methods_supported` will contain `S256` and never
         *     `plain`: `plain` transmits the PKCE verifier unprotected, which
         *     removes the reason PKCE exists.
         */
        get: operations["getOpenIDConfiguration"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/.well-known/jwks.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * JSON Web Key Set
         * @description The public keys token signatures are verified against. Public halves
         *     only — no private parameter ever appears here, which is asserted by a
         *     test that inspects the JSON rather than trusting the serialiser.
         *
         *     Every key that can still verify a token is published, including one
         *     that has stopped signing. That overlap is what lets a key rotate
         *     without invalidating tokens issued moments before it
         *     (`docs/PLAN/09` § Tokens & Keys).
         *
         *     Verification is local: fetch this once, cache it, and validating a
         *     token does not depend on this service being reachable.
         */
        get: operations["getJWKS"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/oauth/authorize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Authorization endpoint (authorization code + PKCE)
         * @description Where single sign-on becomes visible. With a live session this issues
         *     an authorization code and redirects, with nothing rendered; without
         *     one it routes to the hosted login page and resumes afterwards.
         *
         *     **This endpoint does not use the standard error envelope.** OAuth 2.1
         *     defines its own error vocabulary, delivered as query parameters on a
         *     redirect, and that is what a consumer library parses. Every other
         *     endpoint here answers with the `Error` schema; this one answers with
         *     `?error=invalid_request&error_description=...&state=...`.
         *
         *     **PKCE is mandatory for every client type**, public and confidential
         *     alike. `docs/PLAN/05` states this explicitly and it is stricter than OAuth
         *     2.1's baseline: a confidential client's secret protects the token
         *     request, not the code in transit, and a code intercepted from a browser
         *     redirect is useless without the verifier regardless of what the client
         *     can prove later.
         *
         *     `code_challenge_method` must be `S256`. `plain` transmits the verifier
         *     unprotected, which removes the reason PKCE exists.
         *
         *     An invalid `client_id` or an unregistered `redirect_uri` produces a
         *     `400` with an HTML error page and **no redirect at all** — redirecting
         *     to an unvalidated URI to report an error is the open-redirect
         *     vulnerability itself.
         */
        get: operations["authorize"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/oauth/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Token endpoint
         * @description Exchanges an authorization code, a refresh token, or client
         *     credentials for tokens. `docs/PLAN/12` calls this the highest-volume,
         *     most latency-sensitive endpoint in the system.
         *
         *     **This endpoint does not use the standard error envelope.** OAuth 2.1
         *     defines its own JSON error shape — `{"error": "...",
         *     "error_description": "..."}` — and that is what a consumer library
         *     parses.
         *
         *     **Three grants, and two refused by name.** `authorization_code`,
         *     `refresh_token` and `client_credentials` are supported. `password` and
         *     `implicit` return `unsupported_grant_type` with a description saying
         *     the service will never support them, rather than falling through to an
         *     unknown-grant message that leaves an integrator wondering whether they
         *     typed the name wrong.
         *
         *     **Client authentication** is `client_secret_basic` or
         *     `client_secret_post` for confidential clients. Presenting both is
         *     refused. A public client presents only `client_id` and is
         *     authenticated by the PKCE verifier; a confidential client that
         *     presents no secret is `invalid_client` and is never treated as public.
         *
         *     **Every failure to redeem a code returns the same `invalid_grant`.** An
         *     error distinguishing "unknown code" from "wrong redirect_uri" would
         *     tell a holder of a code that the code is real.
         *
         *     The three token types are deliberately different. The ID token is an
         *     assertion about the user with `aud` = your `client_id`; the access
         *     token is a capability at a resource server, carries `typ: at+jwt`
         *     (RFC 9068), and has a different `aud`. A resource server should refuse
         *     an ID token presented as a bearer credential, and the two fields are
         *     what let it.
         */
        post: operations["token"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/oauth/introspect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Token introspection (RFC 7662)
         * @description Answers whether a token is currently good. Most useful for a refresh
         *     token, which is opaque and cannot be inspected any other way.
         *
         *     **Client authentication is required, and the client must be
         *     confidential.** This is stricter than RFC 7662, which leaves the method
         *     open. A public client has no secret, so admitting one would make this
         *     endpoint reachable by anyone who can read a `client_id` out of a
         *     browser URL - a token oracle, which is the one thing it must not be.
         *
         *     **You can only introspect your own tokens.** A token issued to another
         *     client answers `{"active": false}`, exactly as an unknown one does. It
         *     is not an error, because an error would confirm the token exists and
         *     belongs to somebody.
         *
         *     **`{"active": false}` is the answer to everything negative** - unknown,
         *     expired, revoked, malformed, another client's, or one whose session has
         *     since ended. There is no `reason` field and there will not be one: it
         *     would tell a caller holding a captured token whether it ever existed
         *     and whether it has been revoked since.
         *
         *     `username` is not returned, though the RFC lists it. It is an email
         *     address, you already have `sub`, and `/oauth/userinfo` will give you
         *     the address if the user's own token authorises it.
         */
        post: operations["introspect"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/oauth/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Token revocation (RFC 7009)
         * @description Throws a token away deliberately - on logout, on a user disconnecting
         *     an integration, on a suspected leak.
         *
         *     **Always answers `200`**, whether something was revoked, nothing
         *     matched, or the token was already revoked. RFC 7009 section 2.2
         *     requires it, for the same reason introspection has one negative answer:
         *     a status that distinguished the cases is an oracle on whether a guessed
         *     token exists. Revocation is therefore idempotent, and safe to retry.
         *
         *     **You can only revoke your own tokens.** Another client's token is
         *     silently a no-op.
         *
         *     **Revoking a refresh token revokes its whole lineage**, not the single
         *     row - RFC 7009 section 2.1's "tokens based on the same authorization
         *     grant".
         *
         *     **An access token cannot actually be revoked, and this is the one thing
         *     worth reading twice.** It is a signed JWT that nothing looks up, so
         *     presenting one revokes the refresh tokens issued for the same session
         *     and the same client - which stops new access tokens being minted -
         *     while the token you presented keeps working until it expires, up to ten
         *     minutes. If you need it dead sooner, end the session: `/oauth/userinfo`
         *     and every session-backed check stop honouring it immediately.
         *
         *     Public clients may revoke. The operation only destroys a credential the
         *     caller already holds, for its own client.
         */
        post: operations["revoke"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/oauth/userinfo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * UserInfo endpoint
         * @description Returns the claims the presented access token's scopes authorise, and
         *     nothing beyond them.
         *
         *     **Send the token in the `Authorization` header.** RFC 6750 also defines
         *     an `access_token` query parameter and calls it NOT RECOMMENDED; this
         *     service does not accept one. A query parameter is written to the access
         *     log of every proxy in the path, to the browser's history, and to the
         *     `Referer` of whatever the page loads next.
         *
         *     **Scopes decide the claims.** `openid` yields `sub`; `profile` yields
         *     `name`, `preferred_username` and `updated_at`; `email` yields `email`.
         *     A claim outside the granted scopes is never returned, and a claim whose
         *     underlying value is not set is omitted rather than returned empty.
         *
         *     `email_verified` is **not** returned. Nothing in this service verifies
         *     an address yet, and asserting `false` would say we checked and it is
         *     not verified — which we did not.
         *
         *     **`sub` is the user's identifier and is stable.** It is not sequential,
         *     not guessable, and never the email address. Store it as the user's
         *     permanent key; an address may change.
         *
         *     **The token stops working the moment the session behind it ends.** An
         *     access token is not looked up, but the session it was issued from is —
         *     so a logout, a revocation, or a deactivated account invalidates it
         *     immediately rather than at its expiry.
         *
         *     **Every unusable token gets the same answer**: `401` with
         *     `WWW-Authenticate: Bearer error="invalid_token"`. Expired, forged,
         *     wrong audience, and revoked are not distinguished, because a caller
         *     that could tell them apart could ask this endpoint whether a user has
         *     logged out.
         *
         *     A token that is otherwise valid but lacks the `openid` scope gets `403`
         *     with `error="insufficient_scope"`, which is a different thing and is
         *     worth telling you: your token is fine, and it does not cover this.
         */
        get: operations["userinfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe
         * @description Answers whether the process is running. It performs no dependency
         *     checks and cannot fail while the process is able to respond at all.
         *
         *     The distinction from `/readyz` is load-bearing. A liveness probe that
         *     checks the database restarts the service during a database outage,
         *     which converts a recoverable dependency failure into a crash loop that
         *     prevents recovery (`docs/PLAN/14`).
         */
        get: operations["getLiveness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness probe
         * @description Answers whether the process can serve traffic right now, which includes
         *     its dependencies being reachable.
         *
         *     A failure removes this instance from the load balancer without
         *     restarting it — the correct response to a dependency being briefly
         *     unavailable.
         */
        get: operations["getReadiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description OpenID Provider metadata. Fields for unimplemented endpoints are
         *     omitted rather than emitted empty.
         */
        OpenIDConfiguration: {
            /**
             * @description The identifier clients validate the `iss` claim against. Compared
             *     byte for byte, so it never carries a trailing slash.
             * @example https://auth.zedth.my.id
             */
            issuer: string;
            /** @example https://auth.zedth.my.id/.well-known/jwks.json */
            jwks_uri: string;
            /** @description Present once the authorization endpoint exists. */
            authorization_endpoint?: string;
            /** @description Present once the token endpoint exists. */
            token_endpoint?: string;
            userinfo_endpoint?: string;
            revocation_endpoint?: string;
            introspection_endpoint?: string;
            end_session_endpoint?: string;
            response_types_supported?: string[];
            /**
             * @description Never contains `implicit` or `password`: both are ruled out
             *     permanently by `docs/PLAN/05` § Supported Grant Types, and advertising
             *     a grant this service refuses invites a client to build against it.
             */
            grant_types_supported?: string[];
            /**
             * @description `public` only. Pairwise identifiers are a privacy feature this
             *     service does not implement.
             */
            subject_types_supported: string[];
            id_token_signing_alg_values_supported: string[];
            scopes_supported?: string[];
            /** @description `S256` only. Never `plain`. */
            code_challenge_methods_supported?: string[];
            claims_supported?: string[];
        };
        /**
         * @description One public key, per RFC 7517. Private parameters (`d`, `p`, `q`, `dp`,
         *     `dq`, `qi`) never appear.
         */
        JWK: {
            /** @example RSA */
            kty: string;
            /**
             * @description An RFC 7638 thumbprint of the key, so it is stable across restarts
             *     and cannot be chosen by anyone.
             */
            kid: string;
            /** @example sig */
            use: string;
            /** @example RS256 */
            alg?: string;
            /** @description RSA modulus, base64url. */
            n?: string;
            /** @description RSA public exponent, base64url. */
            e?: string;
            /** @description EC curve, for ES256 keys. */
            crv?: string;
            x?: string;
            y?: string;
        };
        JWKS: {
            keys: components["schemas"]["JWK"][];
        };
        /**
         * @description The complete `/healthz` response. There are no other fields, and none
         *     will be added that name a dependency or a version.
         */
        LivenessStatus: {
            /** @enum {string} */
            status: "ok";
        };
        /**
         * @description The complete `/readyz` response.
         *
         *     Note that the ready value is `ready`, not `ok`. The two probes report
         *     different vocabularies, which was found by writing this spec against
         *     the running code rather than from memory. It is recorded accurately
         *     rather than tidied, because a client already parsing `ready` would
         *     break if the server were changed to match a prettier spec — the spec
         *     describes what ships (ADR-013).
         */
        ReadinessStatus: {
            /** @enum {string} */
            status: "ready" | "unavailable";
        };
        /**
         * @description A prefixed, sortable identifier — `usr_`, `org_`, `prj_`, `app_`,
         *     `rol_`, `grt_`. The prefix makes an identifier pasted into a support
         *     ticket self-describing, and makes passing a project id where a user id
         *     belongs visible on sight rather than at the database.
         * @example usr_01HQZX3M8K4N7P2R5T9V6W8Y0B
         */
        ResourceId: string;
        /**
         * @description A stable, machine-readable code. Clients branch on this; `message` is
         *     for humans and may be reworded at any time without a version bump.
         *
         *     Deliberately coarse. A code per failure mode leaks internal structure
         *     and becomes an enumeration oracle — `USER_NOT_FOUND` versus
         *     `PERMISSION_DENIED` tells an attacker which addresses are registered
         *     (`docs/SECURITY/02` §12).
         * @enum {string}
         */
        ErrorCode: "VALIDATION_ERROR" | "UNAUTHENTICATED" | "PERMISSION_DENIED" | "NOT_FOUND" | "CONFLICT" | "RATE_LIMITED" | "INTERNAL";
        /**
         * @description One specific problem within a failed request. Present for
         *     `VALIDATION_ERROR`, where naming the bad field is helpful and discloses
         *     nothing the caller did not send. Generally absent otherwise.
         */
        ErrorDetail: {
            /**
             * @description JSON path to the offending field, relative to the request body.
             * @example email
             */
            field: string;
            /**
             * @description What is wrong with it, in plain language.
             * @example email format is not valid
             */
            issue: string;
        };
        /** @description A successful token response (RFC 6749 § 5.1). */
        TokenResponse: {
            /**
             * @description A JWT with `typ: at+jwt`. Verify it against the JWKS at
             *     `/.well-known/jwks.json` and check `aud` against yourself.
             */
            access_token: string;
            /** @enum {string} */
            token_type: "Bearer";
            /** @description Seconds until the access token expires. */
            expires_in: number;
            /**
             * @description Present when the `openid` scope was granted and a user
             *     authenticated. Absent on a refresh: nothing was authenticated just
             *     now, and an assertion that one had been would be a false statement
             *     with a fresh timestamp on it.
             */
            id_token?: string;
            /**
             * @description Present when the `offline_access` scope was granted. Opaque, not a
             *     JWT — it must be revocable, which a stateless token cannot be.
             */
            refresh_token?: string;
            /** @description The granted scope, space-delimited. */
            scope?: string;
        };
        /**
         * @description The claims the presented access token's scopes authorise.
         *
         *     Only `sub` is guaranteed. Every other property appears when its scope
         *     was granted AND the underlying value is set — an absent claim means the
         *     value is not known or not authorised, and the two are deliberately not
         *     distinguished.
         */
        UserInfo: {
            /**
             * Format: uuid
             * @description The user's stable identifier. Not sequential, not guessable, and
             *     never the email address — store this as the user's permanent key.
             */
            sub: string;
            /** @description Display name. Requires the `profile` scope. */
            name?: string;
            /**
             * @description Requires the `profile` scope. A user may change it, so it is not
             *     an identifier — use `sub`.
             */
            preferred_username?: string;
            /**
             * Format: int64
             * @description Seconds since the epoch, when the user record last changed
             *     (OIDC Core 5.1). Requires the `profile` scope.
             */
            updated_at?: number;
            /**
             * Format: email
             * @description Requires the `email` scope. `email_verified` is deliberately not
             *     returned: nothing in this service verifies an address yet, and
             *     asserting `false` would claim a check that never happened.
             */
            email?: string;
        };
        /**
         * @description RFC 7662's response. When `active` is false it is the ONLY property
         *     present - every negative case answers identically, so nothing here can
         *     be used to tell them apart.
         */
        Introspection: {
            /** @description Whether the token is currently usable. */
            active: boolean;
            /** @description Space-delimited, as granted. */
            scope?: string;
            /**
             * Format: uuid
             * @description The client the token was issued to - always your own.
             */
            client_id?: string;
            /** @enum {string} */
            token_type?: "Bearer";
            /** Format: int64 */
            exp?: number;
            /** Format: int64 */
            iat?: number;
            /**
             * Format: uuid
             * @description The user. Absent for a `client_credentials` token.
             */
            sub?: string;
            aud?: string;
            iss?: string;
        };
        /**
         * @description OAuth 2.1's error shape (RFC 6749 § 5.2), used by the protocol
         *     endpoints. Distinct from the `Error` envelope every other endpoint
         *     returns, because this is what a consumer's OAuth library parses.
         */
        OAuthError: {
            /** @enum {string} */
            error: "invalid_request" | "invalid_client" | "invalid_grant" | "unauthorized_client" | "unsupported_grant_type" | "invalid_scope" | "server_error";
            /**
             * @description Human-readable, and deliberately terse about specifics. It names
             *     what was wrong, never what the correct value would have been.
             */
            error_description?: string;
        };
        /**
         * @description The error envelope for every non-2xx response, without exception
         *     (`docs/PLAN/05` Part B § Standard Error Format). One shape means a client
         *     writes one error path rather than one per endpoint.
         */
        Error: {
            error: {
                code: components["schemas"]["ErrorCode"];
                /**
                 * @description Human-readable, safe to surface in a UI, and never containing a
                 *     token, a password, a raw `/v1/authz/check` resource attribute,
                 *     a stack trace, or a SQL fragment (`docs/PLAN/13`, `CLAUDE.md`).
                 */
                message: string;
                /** @description Field-level problems. Omitted when there are none. */
                details?: components["schemas"]["ErrorDetail"][];
            };
        };
        /**
         * @description The pagination envelope every collection response embeds.
         *
         *     Token-based rather than offset-based: an offset re-reads rows that
         *     shifted under concurrent writes, silently skipping or duplicating
         *     entries. For an audit log or a user list that is a correctness bug that
         *     nobody notices.
         */
        PageInfo: {
            /**
             * @description Pass as `page_token` for the following page. **Absent when there
             *     are no more results** — the presence of this field is the only
             *     valid end-of-collection test. An empty array is not one: a page can
             *     legitimately return zero items and still have a next page.
             */
            next_page_token?: string;
        };
    };
    responses: {
        /** @description The request is malformed or fails validation. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description No access token, or one that is expired, malformed, or revoked. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /**
         * @description Authenticated, but not permitted. Returned for a resource in another
         *     organization even when it exists — distinguishing "forbidden" from "not
         *     found" across a tenant boundary confirms the resource's existence to
         *     someone with no right to know it (`docs/PLAN/08`, `docs/SECURITY/02` §3).
         */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description No such resource, or none visible to this caller. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The request conflicts with the current state, such as a duplicate email. */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /**
         * @description Too many requests. Limits are applied per `client_id` or API key rather
         *     than per IP, so one noisy tenant behind a shared NAT cannot exhaust
         *     another's budget (`docs/PLAN/05` Part B).
         */
        RateLimited: {
            headers: {
                /** @description Requests permitted in the current window. */
                "X-RateLimit-Limit"?: number;
                /** @description Requests left in the current window. */
                "X-RateLimit-Remaining"?: number;
                /** @description Unix seconds at which the window resets. */
                "X-RateLimit-Reset"?: number;
                /** @description Seconds to wait before retrying. */
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /**
         * @description An unexpected failure. The message is deliberately generic; the detail
         *     is correlated by request id in the logs.
         */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /**
         * @description Maximum items to return. The server may return fewer, and returning
         *     fewer never means the collection is exhausted — only an absent
         *     `next_page_token` means that.
         */
        PageSize: number;
        /**
         * @description The `next_page_token` from the previous response. Opaque: its contents
         *     are not part of the contract and must not be constructed, parsed, or
         *     persisted by a client.
         */
        PageToken: string;
        /** @description The organization that owns the resource. Every request is scoped to exactly one. */
        OrganizationId: components["schemas"]["ResourceId"];
        /**
         * @description A client-generated key making a retried `POST` safe. Replaying a
         *     request with the same key returns the original result rather than
         *     creating a second resource — which matters most for automated
         *     provisioning, where a network timeout is indistinguishable from a
         *     failure (`docs/PLAN/05` Part B).
         */
        IdempotencyKey: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getOpenIDConfiguration: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The provider's configuration. */
            200: {
                headers: {
                    /**
                     * @description Cacheable for an hour. The document changes when endpoints are
                     *     added or removed, which is a deploy rather than a routine
                     *     event.
                     */
                    "Cache-Control"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpenIDConfiguration"];
                };
            };
        };
    };
    getJWKS: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The published key set. */
            200: {
                headers: {
                    /**
                     * @description Cacheable for five minutes — deliberately shorter than the
                     *     discovery document. A rotation has to reach every consumer
                     *     inside the overlap window, and this is the bound on how long
                     *     that takes.
                     */
                    "Cache-Control"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/jwk-set+json": components["schemas"]["JWKS"];
                };
            };
            /**
             * @description The key set could not be read. The body names no dependency: this
             *     endpoint is public and unauthenticated (`docs/SECURITY/02` §12).
             */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    authorize: {
        parameters: {
            query: {
                /** @description The application's identifier, which is its `id`. */
                client_id: string;
                /**
                 * @description Where to return. Matched against the client's registered URIs by
                 *     **exact string comparison** — a trailing slash, an added query
                 *     parameter or a different case is a different URI. Not defaulted
                 *     when omitted, even for a client with exactly one registered URI.
                 */
                redirect_uri: string;
                /** @description Only `code` is supported. */
                response_type: "code";
                /**
                 * @description Space-delimited. `openid` is required. `offline_access` requires
                 *     the client to hold the `refresh_token` grant.
                 * @example openid profile email
                 */
                scope: string;
                /**
                 * @description Returned unchanged on every response. Required, which is stricter
                 *     than OAuth demands: this service cannot verify it — only your
                 *     application knows what it sent — so requiring it means a client
                 *     that forgot its CSRF defence finds out at integration time rather
                 *     than in production.
                 */
                state: string;
                /** @description PKCE challenge, base64url, 43-128 characters. */
                code_challenge: string;
                code_challenge_method: "S256";
                /** @description Returned in the `id_token`, for replay detection by the client. */
                nonce?: string;
                /**
                 * @description Space-delimited. `none` never renders UI and returns
                 *     `login_required` instead — which is what a silent renewal in a
                 *     hidden iframe needs. `login` forces re-authentication even with a
                 *     live session, without ending it. `none` cannot be combined with
                 *     any other value.
                 */
                prompt?: string;
                /**
                 * @description Seconds. How recently the user must have **authenticated**, which
                 *     is not the same as how recently they were active.
                 */
                max_age?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /**
             * @description Redirect to `redirect_uri` with `code` and `state`, to the same
             *     place with `error` and `state`, or to the hosted login page.
             */
            302: {
                headers: {
                    Location?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            /**
             * @description `client_id` or `redirect_uri` is not valid. An HTML page, and
             *     deliberately **not** a redirect: there is no validated address to
             *     redirect to, and inventing one is the vulnerability.
             *
             *     The two causes are reported identically, so this cannot be used to
             *     discover which client ids exist (`docs/SECURITY/02` §12).
             */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
        };
    };
    token: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": {
                    /** @enum {string} */
                    grant_type: "authorization_code" | "refresh_token" | "client_credentials";
                    /** @description The authorization code. Required for `authorization_code`. */
                    code?: string;
                    /**
                     * Format: uri
                     * @description Must equal the `redirect_uri` the code was issued for,
                     *     by exact string comparison.
                     */
                    redirect_uri?: string;
                    /**
                     * @description The PKCE verifier. Required for `authorization_code` for
                     *     every client type, including confidential ones.
                     */
                    code_verifier?: string;
                    /** @description Required for `refresh_token`. */
                    refresh_token?: string;
                    /**
                     * @description On a refresh this may narrow the granted scope and may
                     *     never widen it — widening would make the refresh token
                     *     more powerful than the consent that created it.
                     */
                    scope?: string;
                    /** Format: uuid */
                    client_id?: string;
                    /**
                     * @description `client_secret_post`. Use the Authorization header
                     *     instead where you can; presenting both is refused.
                     */
                    client_secret?: string;
                };
            };
        };
        responses: {
            /** @description Tokens. */
            200: {
                headers: {
                    /** @description Always `no-store`. A cached token response is a token handed to whoever asks the cache next. */
                    "Cache-Control"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /**
             * @description `invalid_request`, `invalid_grant`, `unauthorized_client`,
             *     `unsupported_grant_type` or `invalid_scope`.
             */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OAuthError"];
                };
            };
            /**
             * @description `invalid_client`. Carries `WWW-Authenticate: Basic` when Basic
             *     authentication was attempted.
             */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OAuthError"];
                };
            };
        };
    };
    introspect: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": {
                    /** @description The access or refresh token to inspect. */
                    token: string;
                    /**
                     * @description A hint, and only a hint: it decides which lookup is tried
                     *     first and never the outcome. A wrong hint costs one extra
                     *     lookup.
                     * @enum {string}
                     */
                    token_type_hint?: "access_token" | "refresh_token";
                    /** Format: uuid */
                    client_id?: string;
                    /**
                     * @description `client_secret_post`. Prefer the Authorization header;
                     *     presenting both is refused.
                     */
                    client_secret?: string;
                };
            };
        };
        responses: {
            /** @description The answer. `{"active": false}` carries nothing else, deliberately. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Introspection"];
                };
            };
            /** @description `invalid_request` - no token was supplied. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OAuthError"];
                };
            };
            /** @description `invalid_client`. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OAuthError"];
                };
            };
        };
    };
    revoke: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": {
                    token: string;
                    /** @enum {string} */
                    token_type_hint?: "access_token" | "refresh_token";
                    /** Format: uuid */
                    client_id?: string;
                    client_secret?: string;
                };
            };
        };
        responses: {
            /**
             * @description Always, unless the request itself was malformed or the client could
             *     not be authenticated. The body is empty; do not infer anything from
             *     this status about whether a token existed.
             */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description `invalid_request` - no token was supplied. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OAuthError"];
                };
            };
            /** @description `invalid_client`. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OAuthError"];
                };
            };
        };
    };
    userinfo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The claims the granted scopes authorise. */
            200: {
                headers: {
                    /** @description Always `no-store`. The response is personal data addressed to one caller. */
                    "Cache-Control"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserInfo"];
                };
            };
            /**
             * @description The access token is missing, expired, forged, for another
             *     audience, or its session has ended. All of these are the same
             *     answer, deliberately.
             */
            401: {
                headers: {
                    /**
                     * @description `Bearer realm="<issuer>"`, with
                     *     `error="invalid_token"` when a credential was presented.
                     */
                    "WWW-Authenticate"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description The token is valid and does not carry the `openid` scope. */
            403: {
                headers: {
                    /** @description `Bearer error="insufficient_scope", scope="openid"`. */
                    "WWW-Authenticate"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getLiveness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The process is alive. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LivenessStatus"];
                };
            };
        };
    };
    getReadiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ready to serve traffic. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessStatus"];
                };
            };
            /**
             * @description Not ready. The body names no dependency and gives no detail, on
             *     purpose: this endpoint is reachable from the public ingress, and
             *     "which of our dependencies is down" is not something to tell an
             *     anonymous caller. The detail is in the logs and metrics.
             */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessStatus"];
                };
            };
        };
    };
}
